import type { NextPage } from "next";
import Head from "next/head";
import { Provider } from "react-redux";
import { MainPage } from "../src/pages/MainPage";
import { store } from "../src/redux/store";

const Home: NextPage = () => {
  return (
    <Provider store={store}>
      <div>
        <Head>
          <title>Aerolab Challenge</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
            <MainPage />
        </main>
      </div>
    </Provider>
  );
};

export default Home;
